### ISSUE TITLE
`inotify` panics after updating `tokio`

### ISSUE THREAD

**Issue by whfuyn** [cita-cloud/controller_poc#18]
`inotify 0.8.3` internally use `tokio 0.2`. 

After `controller_poc` updating its dependencies to latest (`tokio 1.2`), `inotify` panics at runtime saying that it can't find `tokio`.

Updating `inotify` to latest may solve this problem.

**Comment by rink1969** [comment]
Build is ok, but it will panic when run.
Error info is:
Thread tokio-runtime-worker panicked at there is no reactor running, must be called from the context of a Tokio 0.2.x runtime
